name: build
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  CARGO_TERM_COLOR: always
jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: msrv
      run: |
        msrv=$(cargo metadata --no-deps --format-version 1 |
          jq --raw-output '.packages[] | select(.name=="ndarray-slice") | .rust_version')
        echo "MSRV=$msrv" >> $GITHUB_ENV
    - name: toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ env.MSRV }}
        components: rustfmt, rust-docs, clippy
    - name: test
      run: cargo test
    - name: test-no_std
      run: cargo test --no-default-features --features alloc
    - name: test-no_alloc
      run: cargo test --no-default-features
    - name: test-rayon
      run: cargo test --features rayon -- par::merge_sort::test::stably_sorted par::quick_sort::test::sorted par::partition::test::at_indices
      env:
        QUICKCHECK_GENERATOR_SIZE: 1000000
    - name: clippy
      run: cargo clippy --tests
    - name: doc
      run: cargo doc
    - name: doc-no_std
      run: cargo doc --no-default-features --features alloc
    - name: doc-no_alloc
      run: cargo doc --no-default-features
    - name: doc-rayon
      run: cargo doc --features rayon
    - name: fmt
      run: cargo fmt --check
  nightly:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: rustfmt, rust-docs, clippy, miri
    - name: test
      run: cargo test
    - name: test-no_std
      run: cargo test --no-default-features --features alloc
    - name: test-no_alloc
      run: cargo test --no-default-features
    - name: test-rayon
      run: cargo test --features rayon -- par::merge_sort::test::stably_sorted par::quick_sort::test::sorted par::partition::test::at_indices
      env:
        QUICKCHECK_GENERATOR_SIZE: 1000000
    - name: clippy
      run: cargo clippy --tests
    - name: doc
      run: cargo doc
      env:
        RUSTDOCFLAGS: "--cfg docsrs"
    - name: doc-no_std
      run: cargo doc --no-default-features --features alloc
      env:
        RUSTDOCFLAGS: "--cfg docsrs"
    - name: doc-no_alloc
      run: cargo doc --no-default-features
      env:
        RUSTDOCFLAGS: "--cfg docsrs"
    - name: doc-rayon
      run: cargo doc --features rayon
      env:
        RUSTDOCFLAGS: "--cfg docsrs"
    - name: fmt
      run: cargo fmt --check
    - name: miri
      run: cargo miri test --no-default-features --features std -- Slice1Ext
