name: build
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
env:
  CARGO_TERM_COLOR: always
jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.63.0
        profile: minimal
        components: rustfmt, rust-docs, clippy
        override: true
    - name: test
      uses: actions-rs/cargo@v1
      with:
        command: test
    - name: test-no_std
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-default-features --features alloc
    - name: test-no_alloc
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-default-features
    - name: test-rayon
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features rayon --
          par::merge_sort::test::stably_sorted
          par::quick_sort::test::sorted
          par::partition::test::at_indices
      env:
        QUICKCHECK_GENERATOR_SIZE: 1000000
    - name: clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --tests
    - name: doc
      uses: actions-rs/cargo@v1
      with:
        command: doc
    - name: doc-no_std
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --no-default-features --features alloc
    - name: doc-no_alloc
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --no-default-features
    - name: doc-rayon
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --features rayon
    - name: fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --check
  nightly:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        components: rustfmt, rust-docs, clippy, miri
        override: true
    - name: test
      uses: actions-rs/cargo@v1
      with:
        command: test
    - name: test-no_std
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-default-features --features alloc
    - name: test-no_alloc
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --no-default-features
    - name: test-rayon
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --features rayon --
          par::merge_sort::test::stably_sorted
          par::quick_sort::test::sorted
          par::partition::test::at_indices
      env:
        QUICKCHECK_GENERATOR_SIZE: 1000000
    - name: clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --tests
    - name: doc
      uses: actions-rs/cargo@v1
      with:
        command: doc
      env:
        RUSTDOCFLAGS: "--cfg docsrs"
    - name: doc-no_std
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --no-default-features --features alloc
      env:
        RUSTDOCFLAGS: "--cfg docsrs"
    - name: doc-no_alloc
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --no-default-features
      env:
        RUSTDOCFLAGS: "--cfg docsrs"
    - name: doc-rayon
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: --features rayon
      env:
        RUSTDOCFLAGS: "--cfg docsrs"
    - name: fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --check
    - name: miri
      uses: actions-rs/cargo@v1
      with:
        command: miri
        args: test -- Slice1Ext
